### ISSUE TITLE
First release - feature planning

### ISSUE THREAD

**Issue by Romeeey** [GothicVRProject/GothicVR#111] opened 2023-06-12 09:09 UTC
We plan a first release on the basis of our new approach unZENity.
The focus of our initial release is to provide our users the entire Gothic 1 world plus items.

### Goals
**The big focus of the release**

* World
* Items

### Non goals
**Explicit non goals. Spared for later releases when implementation is more progressed.**

* NPCs
* Animations

### Debatable goals
**Features are connected to the focus of the release. If they are far / good enough, we can include them.**
* Item grabbing (if it works basically, tests can send us screenshots to correct it afterwards)
* Chests (is really a nice to have)
* Sound (if some ambient sounds are available, this would be nice, but no must)

### Obligatory

- [x] All world meshes available
- [x] All textures available
- [x] All position and rotation problems solved (if there are still any)
- [x] Basic movement settings (in progress by @Romeeey)
- [x] Trees and vegetation visualized nicely (no black block trees)
- [x] Invisible walls hidden (no white or black walls on stage and arena)
- [x] Alpha values for leather on pallisades corrected (transparent, not black boxes)
- [x] Performance good enough so that it runs with PCVR

### Optional / Nice to have

- [x] #139
- [x] Skybox with Gothic textures (better than just a bright blue sky)
- [x]  Running water animation / shader (was implemented by vince in the old PoC, maybe can be taken over)
- [x] Enter water (currently water is solid ground, (was implemented by vince in the old PoC, maybe can be taken over)
- [ ] Item label for items (might not be necessary and to much at the moment, up for discussion)
- [x] Performance good enough to run also on standalone glasses like Quest 2 and Pico 4.

## Version number

As discussed in discord I suggest we start with a new numbering. 
Either with 0.1 or with something generated from CI.

Suggestion @JaXt0r:
https://semver.org/

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

## Time frame

I suggest we announce the release in our discord channels in 1-2 weeks and then release within the next 1-2 months. In terms of deadlines / pressure we can also just not announce and work internally towards the goal.

**Comment by JaXt0r** [comment] 2023-08-26 04:29
@Romeeey except one item, we're fine with this ticket. Feel free to close it as duplicate of #178

**Closed** 2023-10-23 11:07 UTC
Labels: documentation
