### ISSUE TITLE
Chest opening

### ISSUE THREAD

**Issue by Romeeey** [GothicVRProject/GothicVR#114] opened 2023-06-12 20:29 UTC
Chests are all over the world of Gothic 1.
We want to have them in VR as well and also interact with them.

### Option 1: Press open + play chest opening animation

A VR player gets a context sensitive button that says "Open"
Alternatively the VR hands simply interact / collide with the chest lock.

After triggering the chest (by "open" button or gripping the chest lock), the opening animation is played.
So the chest lid opens automatically / swings open.

### Option 2: VR grab opening

The lid is a movable item, that can be opened (it's static but rotates around the hinges).
Opening means grabbing the lid and pulling it open.

The lid shall stay in place, when it has reached the opened state.
The lid shall either fall back to the closed state or stay in the position, when the VR player doesn't grip anymore.

## Locked chests with key

The key is grabbed and put with the player's VR hands into the chest lock.
Then both opening options are again possible. The lid either swings open or the player needs to use his VR hands to activly open / manipulate the lid.

## Pick locking

Similar to the key feature, but with a pick lock.
Picklocking feature is a dedicated ticket. 

### Option 1: Slots

Items in chests are placed in slots.
Items can be taken out of slots or placed in slots. The slots shall have a stacking feature (like eg 50 ore).

Question: How many slots shall there be? How about chests that are pretty full? 
Pro: Easy to interact with
Con: Feels gamey, not realistic 

### Option 2: Items lie messily in the chest

Items are not properly placed in slots but just lie around messily.
Pro: More realistic, less gamey
Con: Messy, not really comfortable to interact with.

### General thoughts

Both variations could be implemented and made optional in the settings.
We also need to think about proper stacking features (eg. I want to take 30 ore of the 50 ore in a slot).
We need a grab all / take all feature for chests.

**Comment by JaXt0r** [comment] 2023-06-14 06:44
Hint: We get opening animation from Gothic itself. I recommend we adapt our opening interaction (either via hands or button click) to execute this animation.

**Comment by JaXt0r** [comment] 2023-06-14 06:45
Partially duplicate of https://github.com/GothicVRProject/GothicVR/issues/101

**Comment by JaXt0r** [comment] 2024-01-01 10:40
Duplicate of https://github.com/GothicVRProject/GothicVR/issues/228

**Closed by JaXt0r** 2024-01-01 10:40 UTC
